# Generated by Django 3.1.4 on 2020-12-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('learned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyburgs.learned')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('ordinal_number', models.TextField(null=True)),
                ('name_suffix', models.TextField(null=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('birthplace', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('habsburg_ancestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habsburg_ancestor_person', to='studyburgs.person')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date_time', models.DateTimeField()),
                ('note_for_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studyburgs.person')),
                ('note_for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studyburgs.user')),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_marriage', models.DateField()),
                ('comments', models.TextField(null=True)),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband_marriage', to='studyburgs.person')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife_marriage', to='studyburgs.person')),
            ],
        ),
        migrations.AddField(
            model_name='learned',
            name='learned_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyburgs.person'),
        ),
    ]
