# Generated by Django 3.1.4 on 2021-01-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture_url',
            field=models.TextField(null=True),
        ),
    ]
