# Generated by Django 3.1.4 on 2021-01-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0002_person_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyburgsuser',
            name='groupsReference',
            field=models.TextField(null=True),
        ),
    ]
