# Generated by Django 3.1.4 on 2021-01-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0003_studyburgsuser_groupsreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
