# Generated by Django 3.1.4 on 2021-01-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0004_notes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthplace',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_suffix',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='ordinal_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_url',
            field=models.TextField(default=''),
        ),
    ]
