# Generated by Django 3.1.4 on 2021-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0006_auto_20210128_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthplace',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_suffix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='ordinal_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
