# Generated by Django 3.1.4 on 2021-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0007_auto_20210128_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ordinal_number',
            field=models.TextField(default=''),
        ),
    ]
