# Generated by Django 3.1.4 on 2021-01-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0010_auto_20210128_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ordinal_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
