# Generated by Django 3.1.4 on 2021-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyburgs', '0011_auto_20210128_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
